// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm1rmMUgWQ1OBPGOz9PkpBCtGj6qis71U',
    appId: '1:588116752649:web:035d725f48cfe2110ffbd8',
    messagingSenderId: '588116752649',
    projectId: 'riego-inteligente-e4a28',
    authDomain: 'riego-inteligente-e4a28.firebaseapp.com',
    databaseURL: 'https://riego-inteligente-e4a28-default-rtdb.firebaseio.com/',
    storageBucket: 'riego-inteligente-e4a28.appspot.com',
    measurementId: 'G-T8PN8T5LNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN8W0DEYAvNE3R4SEI2BUuqj2SAPAfFag',
    appId: '1:588116752649:android:01516fd5b0fd26890ffbd8',
    messagingSenderId: '588116752649',
    projectId: 'riego-inteligente-e4a28',
    databaseURL: 'https://riego-inteligente-e4a28-default-rtdb.firebaseio.com/',
    storageBucket: 'riego-inteligente-e4a28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtO6cIQKnd1cUhzgjr1qp-WZCJN566w9k',
    appId: '1:588116752649:ios:a936aa48c1c2752e0ffbd8',
    messagingSenderId: '588116752649',
    projectId: 'riego-inteligente-e4a28',
    storageBucket: 'riego-inteligente-e4a28.appspot.com',
    iosClientId:
        '588116752649-4708cbjnbbnn11kbd7jq67o3bs5mjnha.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicacionRiego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtO6cIQKnd1cUhzgjr1qp-WZCJN566w9k',
    appId: '1:588116752649:ios:a936aa48c1c2752e0ffbd8',
    messagingSenderId: '588116752649',
    projectId: 'riego-inteligente-e4a28',
    storageBucket: 'riego-inteligente-e4a28.appspot.com',
    iosClientId:
        '588116752649-4708cbjnbbnn11kbd7jq67o3bs5mjnha.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicacionRiego',
  );
}
